# Generated by Django 4.0.1 on 2022-01-10 02:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(20), django.core.validators.ProhibitNullCharactersValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(250), django.core.validators.ProhibitNullCharactersValidator()])),
                ('author', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator("^[A-Z][A-Za-z \\-']$"), django.core.validators.ProhibitNullCharactersValidator()])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='quotes', to='quotes.Tag')),
            ],
            options={
                'ordering': ('id',),
                'unique_together': {('id', 'text', 'author')},
            },
        ),
    ]
